/**
 * ITMO.Maps API
 * ITMO.Maps backend server
 *
 * OpenAPI spec version: dev
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.haze.itmomaps.network

/**
 *
 * @param x
 * @param y
 * @param floor
 */
data class CoordinatesView(
        val x: kotlin.Int? = null,
        val y: kotlin.Int? = null,
        val floor: kotlin.Int? = null
)

