/**
 * ITMO.Maps API
 * ITMO.Maps backend server
 *
 * OpenAPI spec version: dev
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.haze.itmomaps.network

/**
 *
 * @param coordinates
 * @param type
 * @param name
 * @param description
 */
data class MapObjectView(
        val coordinates: CoordinatesView? = null,
        val type: kotlin.String? = null,
        val name: kotlin.String? = null,
        val description: kotlin.String? = null
)

