/**
 * ITMO.Maps API
 * ITMO.Maps backend server
 *
 * OpenAPI spec version: dev
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.example.haze.itmomaps.network

/**
 *
 * @param floor
 * @param url
 */
data class PictureView(
        val floor: kotlin.Int? = null,
        val url: kotlin.String? = null
)

